# -*- coding: utf-8 -*-
"""Untitled177.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-BGnLuTgMzXiQjH2YdElLeP0f5nTQ64b
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

dataset1 = pd.read_csv('/content/amazon.csv',encoding="ISO-8859-1")

dataset1

"""# Converting Date Column dtype"""

dataset1['date'] = pd.to_datetime(dataset1['date'])
dataset1.info()

"""#Top 5 Rows of The Dataset"""

dataset1.head()

"""# Last 5 Rows"""

dataset1.tail()

"""# Shape of Our Dataset (Number of Rows And Number of Columns)"""

dataset1.shape

"""# Getting Information About Our Dataset Like Total Number Rows, Total Number of Columns, Datatypes of Each Column And Memory Requirement"""

dataset1.info()

"""# Check For Duplicate Data and Drop Them"""

dataset1 = dataset1.drop_duplicates()
dataset1.info()
#So total (6454-6422) = 32 are duplicated

"""# Check Null Values In The Dataset"""

dataset1.isnull().sum()

"""# Get Overall Statistics About The Dataframe"""

dataset1.describe()

"""# Rename Month Names To English"""

dataset1['month_name'] = dataset1['month'].map({'Janeiro':'january',
'Fevereiro':'febuary',
'Março':'march',
'Abril':'april',
'Maio':'may',
'Junho':'june',
'Julho':'july',
'Agosto':'august',
'Setembro':'september',
'Outubro':'october',
'Novembro':'november',
'Dezembro':'december'})

dataset1

"""# In Which Month Maximum Number of Forest Fires Were Reported?"""

max_fire = dataset1.groupby('month_name')['number'].sum().reset_index()
max_fire

plt.figure(figsize=(16,5))
sns.barplot(x='month_name',y='number',data=max_fire)

"""# In Which Year Maximum Number of Forest Fires Was Reported?"""

max_fire_year = dataset1.groupby('year')['number'].sum().reset_index()
max_fire_year

plt.figure(figsize=(16,5))
sns.barplot(x='year',y='number',data=max_fire_year)

"""# In Which State Maximum Number of Forest Fires Was Reported?"""

max_fire_state = dataset1.groupby('state')['number'].sum().reset_index()
max_fire_state

plt.figure(figsize=(16,5))
plt.xticks(rotation=75)
sns.barplot(x='state',y='number',data=max_fire_state)

"""#  Total Number of Fires Were Reported In Amazonas"""

dataset1[dataset1['state'] == 'Amazonas']['number'].sum()

"""# Display Number of Fires Were Reported In Amazonas (Year-Wise)"""

amazona = dataset1[dataset1['state'] == 'Amazonas']
amazona1 = amazona.groupby('year')['number'].sum().reset_index()
amazona1

plt.figure(figsize=(15,6))
sns.barplot(x='year',y='number',data=amazona1)

"""# Display Number of Fires Were Reported In Amazonas (Day-Wise)"""

amazona3 = dataset1[dataset1['state'] == 'Amazonas']
week = amazona3.groupby(amazona3['date'].dt.dayofweek).sum().number

import calendar
week.index = [calendar.day_name[x] for x in range(0,7)]

week = week.reset_index()

sns.barplot(x='index',y='number',data=week)

"""# Find Total Number of Fires  Were Reported In 2015 And Visualize Data Based on Each ‘Month’"""

data3 = dataset1[dataset1['year']==2015]
fire = data3.groupby('month_name')['number'].sum().reset_index()

plt.figure(figsize=(15,6))
sns.barplot(x='month_name',y='number',data=fire)

"""# Find Average Number of Fires Were Reported From Highest to Lowest (State-Wise)"""

state_avg = dataset1.groupby('state')['number'].mean().sort_values(ascending= False).reset_index()
state_avg

sns.barplot(x='state',y='number',data=state_avg)
plt.xticks(rotation=75)
plt.show()

"""# To Find The State Names Where Fires Were Reported In 'dec' Month"""

dataset1[dataset1['month_name']=='december']['state'].unique()