# -*- coding: utf-8 -*-
"""Untitled172.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WKKSc-iSicy_ebYede2oFPy--jj0Kabn
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

dataset = pd.read_csv('/content/Ecommerce Purchases')

"""Top 5 Columns"""

dataset.head()

"""Some Basic INFO about data"""

dataset.info

"""### Checking Null Values

"""

dataset.isnull().sum()

dataset.shape

dataset.columns

"""Checking highest and lowest purchase price"""

dataset['Purchase Price'].max()

dataset['Purchase Price'].min()

"""Average Purchase Price

"""

dataset['Purchase Price'].mean()

"""How many people have french(fr) as their native language

"""

len(dataset[dataset['Language'] == 'fr'])

"""Job Title that contains engineer"""

len(dataset[dataset['Job'].str.contains('engineer',case=False)])

"""Find email of the person with ip address 132.207.160.22"""

dataset[dataset['IP Address'] == '132.207.160.22']['Email']

"""How Many people have mastercard as payment method and purchase above 50"""

len(dataset[(dataset['CC Provider'] == 'Mastercard') & (dataset['Purchase Price']>50)])

"""Find the email of the person with the following Credit Card Number: 4664825258997302"""

dataset[dataset['Credit Card'] == 4664825258997302]['Email']

"""How many people purchase during the AM and how many people purchase during PM?"""

dataset['AM or PM'].value_counts()

"""How many people have a credit card that expires in 2020?"""

len(dataset[dataset['CC Exp Date'].apply(lambda x:x[3:]=='20')])

"""What are the top 5 most popular email providers (e.g. gmail.com, yahoo.com, etc...)


"""

list1 = []
for email in dataset['Email']:
  list1.append (email.split('@')[1])

dataset['email_provider'] = list1
dataset['email_provider'].value_counts().head(5)